### PR TITLE
Working version of Develop with test coverage for production deployment

### PR DESCRIPTION
**Pull request by Johanndutoit**
First version that past tests and has had some testing on QA with the Praekelt SideLoader

### CODE REVIEW

**Comment by Johanndutoit** [comment]
@smn the long awaited merge

**Comment by smn** [comment]
:+1: because at this point it's too long to review.

**Comment by smn** [comment]
`git flow release X.X.X` helps for this kind of stuff, that does a tagged release (in git) and merges that commit into master as well so `master` always points at your latest tagged commit and `develop` can be ahead of that still.

**Comment by Johanndutoit** [comment]
closing this PR as we already merged ...

**Pull request closed without merging**
