### PR TITLE
Increase coverage percentage.

### PR DESCRIPTION
**Pull request by smn**
Just creating a ticket so we can create the coverage branch into a pull request.

### CODE REVIEW

**Comment by smn** [comment]
Looks like db schema isn't being applied when tests are run, I suspect the following may make that happen but I'm not sure:

``` diff
diff --git a/goddard/schema.coffee b/goddard/schema.coffee
index e7ff734..c554abd 100644
--- a/goddard/schema.coffee
+++ b/goddard/schema.coffee
@@ -219,10 +219,12 @@ module.exports = exports = (app) ->

    })

-   # sync all the tables
-   # sequelize.sync({ force: true })
+   # check according to if we are currently in testing or production
+   if process.env.NODE_ENV or '' == 'testing'
+       sync all the tables
+       sequelize.sync({ force: true })

-   # create our schema 
+   # create our schema
    app.set('models', Models)
    app.set('sequelize', Sequelize)
    app.set('sequelize_instance', sequelize)
```

**Comment by Johanndutoit** [comment]
The schema is synced over at https://github.com/praekelt/goddard-hub-server/pull/28/files#diff-d2be1435e1064d2c97b91db82193229aR14 acts as a Harness for al the handler related tests that need a mock database

**Comment by Johanndutoit** [comment]
@smn ^ seems we are a go. Will be adding in all the badges so we can see actual coverage next.

**Comment by smn** [comment]
@Johanndutoit thanks but it looks like the coverage data's not yet being published to coveralls yet? It's complaining about not finding the lcov.info file (which may be because of me setting it up wrong).

**Comment by smn** [comment]
Coverage now being reported at https://coveralls.io/github/praekelt/goddard-hub-server and here in the pull-request. Please land this so we can improve incrementally from here onwards.

**Comment by Johanndutoit** [comment]
@smn doing some testing will then merge. Sitting at 78% which I'll increment slowly as I add a few more tests. Assuming once it its master sideloader takes over for the deployment ?

**Comment by Johanndutoit** [comment]
^ by testing I mean checking that all the node endpoints etc are still good when actually sending real data to them ..

**Comment by smn** [comment]
Once it's in the default branch (generally that is `develop` sideloader will kick off a build). I'll check how @calston has wired things up around deploys to QA servers and such.

**Comment by smn** [comment]
Yup, a merge of a feature branch will result in a deploy to the QA server.

**Pull request merged**
