### PR TITLE
Allow apps to specify how the docker command needs to be run.

### PR DESCRIPTION
**Pull request by smn**
Some docker apps have specific environment variables that need to be set or extra entrypoint arguments.

### CODE REVIEW

**Comment by smn** [comment]
@bruskiza & @Johanndutoit pls review, I'm a bit unsure about this node / coffee stuff.

**Comment by smn** [comment]
There's a [docker image](http://garelay.rtfd.org) I'm considering deploying on the test server in Cape Town but it needs some extra arguments to run it, the default `docker run` won't do it. This adds a field to the apps model that allows us to specify a custom command that may be needed to run the docker container.

**Comment by bruskiza** [comment]
:+1:

**Comment by smn** [comment]
Hm, looks like the migration isn't being applied.

**Pull request merged**
