### PR TITLE
Feature/downloaders

### PR DESCRIPTION
**Pull request by Johanndutoit**
Added a token section.

That allows creating and revoking tokens. Then added that logic into the download url. So downloads can now be made with the token.

Tokens are given a friendly name and can be revoked. But not edited.

Also added a few tests for the suite for these new pages.

### CODE REVIEW

**Comment by smn** [comment]
@Johanndutoit thanks for this. The only thing I'm missing is how does the 3rd party get notified of a new build? Currently the builds are timestamped but how does one know when a new build has been made on a certain day?

**Comment by smn** [comment]
I've read the code again, if I'm understanding things correctly the token automatically results in the latest build being streamed as a download, I'm still unclear on how a 3rd party would know (or get prompted) to download a new build.

**Comment by Johanndutoit** [comment]
@smn hey, well that in my mind happens in the build script on the server. So the build is done, filename generated, file saved, push notification made. Then the push notification would just contain the url to download the file. Somewhere along the line adding the token or just sending the raw url where the client will then add their auth token to download the file.

**Comment by Johanndutoit** [comment]
@smn also on your second comment. This endpoint and tokens are meant to be able to just authorise and download the files. So the actual build happens on the server, and these endpoints allow you to auth and download the builds.

**Pull request merged**
