### PR TITLE
Updated to make the "warnings" field NULL instead of a blank array

### PR DESCRIPTION
**Pull request by Johanndutoit**
This was changed to accommodate SQLite for unit tests. 

So now if no warnings are given the field is instead set as a "NULL".

### CODE REVIEW

**Comment by Johanndutoit** [comment]
@jonathanendersby @BarryBotha thoughts ?

**Comment by smn** [comment]
Looks reasonable, is there a way to verify in a test that no warnings have been raised in the DB layer?

**Comment by Johanndutoit** [comment]
@smn not quite sure what you mean ? So no errors raised from Postgres while setting to NULL ?

Have added unit test to check this specific use case and updated to actually check the local variable instead rather then using the nodes warning object.

**Comment by Johanndutoit** [comment]
@jonathanendersby @BarryBotha thoughts, if any ?

**Comment by smn** [comment]
Thanks for the test. My Coffeescript isn't good enough to determine if the `if node_obj.warnings` check also works for an `[]` in CS. I tried it in Javascript and `[]` seems to resolve to `true` there so :+1: from me.

**Pull request merged**
